name: Publish to Exchange & Deploy to CH2.0

on:
  pull_request:
    types: [closed]
    branches: [ main ]
    
jobs:         
  build:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'develop'
    runs-on: self-hosted
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17

      # Create settings.xml for Maven authentication
      - name: Create settings.xml
        uses: s4u/maven-settings-action@v3.0.0
        with:
          # This flag ensures any existing settings.xml is completely replaced
          override: true
          # servers: |
          #   [
          #     {
          #       "id": "anypoint-exchange-v3",
          #       "username": "${{ secrets.USERNAME }}",
          #       "password": "${{ secrets.PASSWORD }}"
          #     }
          #   ]

      - name: Publish to Exchange
        run: |
          mvn deploy --settings .maven/settings.xml -DskipMunitTests \
          -DconnectedApp.clientId="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
          -DconnectedApp.clientSecret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}"

      - name: Deploy to CloudHub 2.0
        run: |
          mvn deploy --settings .maven/settings.xml -DskipMunitTests -DmuleDeploy \
          -DconnectedApp.clientId=${{ secrets.CONNECTED_APP_CLIENT_ID }} \
          -DconnectedApp.clientSecret=${{ secrets.CONNECTED_APP_CLIENT_SECRET }} \
          -Dmule.env=dev
